/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mvcguifinal;

import javax.swing.JOptionPane;

/**
 *
 * @author alexa
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCRUDEspecies = new javax.swing.JButton();
        btnCRUDClientes = new javax.swing.JButton();
        btnCRUDProductos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("         MENU VITALPET");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 30));

        btnCRUDEspecies.setBackground(new java.awt.Color(0, 204, 204));
        btnCRUDEspecies.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        btnCRUDEspecies.setText("ESPECIES");
        btnCRUDEspecies.addActionListener(this::btnCRUDEspeciesActionPerformed);
        getContentPane().add(btnCRUDEspecies, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 140, 40));

        btnCRUDClientes.setBackground(new java.awt.Color(0, 204, 204));
        btnCRUDClientes.setText("𝓒𝓛𝓘𝓔𝓝𝓣𝓔");
        btnCRUDClientes.addActionListener(this::btnCRUDClientesActionPerformed);
        getContentPane().add(btnCRUDClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 137, 39));

        btnCRUDProductos.setBackground(new java.awt.Color(0, 204, 204));
        btnCRUDProductos.setText("𝓟𝓡𝓞𝓓𝓤𝓒𝓣𝓞𝓢");
        btnCRUDProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCRUDProductos.addActionListener(this::btnCRUDProductosActionPerformed);
        getContentPane().add(btnCRUDProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 139, 43));

        btnSalir.setBackground(new java.awt.Color(204, 204, 255));
        btnSalir.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/505055.jpeg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null,"Fin de ejecucion :)");
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCRUDClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCRUDClientesActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gestion de Clientes ");
        menu_clientes ingresar = new menu_clientes();
        ingresar.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnCRUDClientesActionPerformed

    private void btnCRUDProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCRUDProductosActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gestion de Productos ");
        menu_productos ingresar = new menu_productos();
        ingresar.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnCRUDProductosActionPerformed

    private void btnCRUDEspeciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCRUDEspeciesActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, " Especies de Mascotas ");
        menu_especies ingresar = new menu_especies();
        ingresar.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnCRUDEspeciesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCRUDClientes;
    private javax.swing.JButton btnCRUDEspecies;
    private javax.swing.JButton btnCRUDProductos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
