/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mvcguifinal;
import controller.especiesController;
/**
 *
 * @author ASUS
 */
public class menu_especies extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(menu_especies.class.getName());

    /**
     * Creates new form menu_especies
     */
    public menu_especies() {
        initComponents();
        especiesController tabla = new especiesController(this);
        tabla.ListarEspecies();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombreEsp = new javax.swing.JTextField();
        txtDescripcionEsp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tabla = new javax.swing.JScrollPane();
        tblEspecies = new javax.swing.JTable();
        btnADDEspecies = new javax.swing.JButton();
        btnActualizarEsp = new javax.swing.JButton();
        btnEliminarEsp = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gg.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gg.png"))); // NOI18N
        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Especies / Mascotas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 480, -1));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 24)); // NOI18N
        jLabel6.setText("Descripcion");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));
        getContentPane().add(txtNombreEsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 130, 110, 30));
        getContentPane().add(txtDescripcionEsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 110, 30));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 24)); // NOI18N
        jLabel5.setText("Nombre");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        tblEspecies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "DESCRIPCION"
            }
        ));
        tblEspecies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEspeciesMouseClicked(evt);
            }
        });
        tabla.setViewportView(tblEspecies);

        getContentPane().add(tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 350, 110));

        btnADDEspecies.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnADDEspecies.setForeground(new java.awt.Color(255, 51, 102));
        btnADDEspecies.setText("Insertar");
        btnADDEspecies.addActionListener(this::btnADDEspeciesActionPerformed);
        getContentPane().add(btnADDEspecies, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        btnActualizarEsp.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnActualizarEsp.setForeground(new java.awt.Color(102, 102, 255));
        btnActualizarEsp.setText("Actualizar");
        btnActualizarEsp.addActionListener(this::btnActualizarEspActionPerformed);
        getContentPane().add(btnActualizarEsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        btnEliminarEsp.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnEliminarEsp.setForeground(new java.awt.Color(0, 204, 153));
        btnEliminarEsp.setText("Eliminar");
        btnEliminarEsp.addActionListener(this::btnEliminarEspActionPerformed);
        getContentPane().add(btnEliminarEsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        btnLimpiar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 153, 51));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        btnRegresar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(153, 0, 153));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gg.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnADDEspeciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDEspeciesActionPerformed
        // TODO add your handling code here:
        especiesController control = new especiesController(this);
        control.insertarEspecies();
        limpiar();
    }//GEN-LAST:event_btnADDEspeciesActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        Menu inicio=new Menu();
        inicio.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnActualizarEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarEspActionPerformed
        // TODO add your handling code here:
        especiesController cc = new especiesController(this);
        cc.actualizarEspecies();
        limpiar();
    }//GEN-LAST:event_btnActualizarEspActionPerformed

    private void tblEspeciesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEspeciesMouseClicked
        // TODO add your handling code here:
        int fila = tblEspecies.getSelectedRow();
        if (fila >= 0) {
        String id = tblEspecies.getValueAt(fila, 0).toString();
        String nombre = tblEspecies.getValueAt(fila, 1).toString();
        String descripcion = tblEspecies.getValueAt(fila, 2).toString();

        txtNombreEsp.setText(nombre);
        txtDescripcionEsp.setText(descripcion);
    }//GEN-LAST:event_tblEspeciesMouseClicked
    }
    private void btnEliminarEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEspActionPerformed
        // TODO add your handling code here:
        especiesController control = new especiesController(this);
        control.eliminarEspecies();
        limpiar();
    }//GEN-LAST:event_btnEliminarEspActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new menu_especies().setVisible(true));
    }
public void limpiar() {
    txtNombreEsp.setText("");
    txtDescripcionEsp.setText("");
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADDEspecies;
    private javax.swing.JButton btnActualizarEsp;
    private javax.swing.JButton btnEliminarEsp;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane tabla;
    public javax.swing.JTable tblEspecies;
    public javax.swing.JTextField txtDescripcionEsp;
    public javax.swing.JTextField txtNombreEsp;
    // End of variables declaration//GEN-END:variables
}
