/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mvcguifinal;

import controller.clientesController;

/**
 *
 * @author alexa
 */
public class menu_clientes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(menu_clientes.class.getName());

    /**
     * Creates new form menu_clientes
     */
    public menu_clientes() {
        initComponents();
        clientesController tabla = new clientesController(this);
        tabla.ListarClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCedulaCli = new javax.swing.JTextField();
        txtNombreCli = new javax.swing.JTextField();
        txtApellidoCli = new javax.swing.JTextField();
        txtEmailCli = new javax.swing.JTextField();
        cbxGeneroCli = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtADireccionCli = new javax.swing.JTextArea();
        cbxEstadoCli = new javax.swing.JComboBox<>();
        btbGuardarCli = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnEliminarClie = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnActualizarCli = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/303003030030.jpeg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Gestion de clientes ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 150, 24));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Cedula");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 36, 63, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 64, 63, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("  Apellido");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 63, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("  Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 63, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Genero");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 172, 63, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Estado");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 200, 63, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText(" Direccion ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 63, -1));
        getContentPane().add(txtCedulaCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 100, -1));
        getContentPane().add(txtNombreCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 100, -1));
        getContentPane().add(txtApellidoCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 100, -1));
        getContentPane().add(txtEmailCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 100, -1));

        cbxGeneroCli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        getContentPane().add(cbxGeneroCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 100, -1));

        txtADireccionCli.setColumns(20);
        txtADireccionCli.setRows(5);
        jScrollPane1.setViewportView(txtADireccionCli);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 157, 45));

        cbxEstadoCli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        getContentPane().add(cbxEstadoCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 100, -1));

        btbGuardarCli.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btbGuardarCli.setText("Guardar");
        btbGuardarCli.addActionListener(this::btbGuardarCliActionPerformed);
        getContentPane().add(btbGuardarCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Cedula", "Nombre", "Apellido", "Email", "Genero", "Estado", "Direccion"
            }
        ));
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblClientes);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 390, 200));

        btnEliminarClie.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarClie.setText("Eliminar");
        btnEliminarClie.addActionListener(this::btnEliminarClieActionPerformed);
        getContentPane().add(btnEliminarClie, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        btnActualizarCli.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizarCli.setText("Actualizar");
        btnActualizarCli.addActionListener(this::btnActualizarCliActionPerformed);
        getContentPane().add(btnActualizarCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/303003030030.jpeg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        Menu inicio=new Menu();
        inicio.setVisible(true);
        
        this.dispose();
        limpiar();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btbGuardarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbGuardarCliActionPerformed
        // TODO add your handling code here:
        clientesController control = new clientesController(this);
        control.insertarClientes();
        limpiar();
    }//GEN-LAST:event_btbGuardarCliActionPerformed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        // TODO add your handling code here:
        int fila = tblClientes.getSelectedRow();
        if (fila>=0){
           
            String cedula = tblClientes.getValueAt(fila,1).toString();
            String nombre =tblClientes.getValueAt(fila,2).toString();
            String apellido = tblClientes.getValueAt(fila, 3).toString();
            String email = tblClientes.getValueAt( fila,4).toString();
            String genero = tblClientes.getValueAt( fila,5).toString();
            String estado = tblClientes.getValueAt( fila,6).toString();
            String direccion = tblClientes.getValueAt(fila,7).toString();
            String id =tblClientes.getValueAt( fila,0).toString();
            
            
            txtCedulaCli.setText(cedula);
            txtNombreCli.setText(nombre);
            txtApellidoCli.setText(apellido);
            txtEmailCli.setText(email);
            cbxGeneroCli.setSelectedItem(genero);
            cbxEstadoCli.setSelectedItem(estado);
            txtADireccionCli.setText(direccion);
        }
        
    }//GEN-LAST:event_tblClientesMouseClicked

    private void btnEliminarClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClieActionPerformed
        // TODO add your handling code here:
        clientesController control = new clientesController(this);
        control.eliminarClientes();
        limpiar();
    }//GEN-LAST:event_btnEliminarClieActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnActualizarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarCliActionPerformed
        // TODO add your handling code here:
        clientesController cc = new clientesController(this);
        cc.actualizarClientes();
        limpiar();
    }//GEN-LAST:event_btnActualizarCliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new menu_clientes().setVisible(true));}
        public void limpiar(){
            txtCedulaCli.setText("");
            txtNombreCli.setText("");
            txtApellidoCli.setText("");
            txtEmailCli.setText("");
            cbxGeneroCli.setSelectedItem(0);
            cbxEstadoCli.setSelectedItem(0);
            txtADireccionCli.setText("");
        }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbGuardarCli;
    public javax.swing.JButton btnActualizarCli;
    public javax.swing.JButton btnEliminarClie;
    public javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegresar;
    public javax.swing.JComboBox<String> cbxEstadoCli;
    public javax.swing.JComboBox<String> cbxGeneroCli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tblClientes;
    public javax.swing.JTextArea txtADireccionCli;
    public javax.swing.JTextField txtApellidoCli;
    public javax.swing.JTextField txtCedulaCli;
    public javax.swing.JTextField txtEmailCli;
    public javax.swing.JTextField txtNombreCli;
    // End of variables declaration//GEN-END:variables
}
